apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-db
  labels:
    app: postgresql-pod
  annotations:
    description: "Postgresql configmap"
data:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres