apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-order-app
data:
  Settings__RabbitMQ__ConnectionString: amqp://guest:guest@svc-rabbitmq
  Settings__PostgreSQL__ConnectionString: Host=svc-postgres;Port=5432;Database=OrderService;Username=postgres;Password=postgres
  Settings__MinIO__Endpoint: play.min.io
  Settings__MinIO__AccessKey: KZiVbMtAbJDVxL5CZ5Kv
  Settings__MinIO__SecretKey: 0NbNFEFgK9e2mu4rHkbLuQK2ViBNkTbxCmR5oenu
  Settings__Auth__Key: randomlyGeneratedKey12345randomlyGeneratedKey12345randomlyGeneratedKey12345randomlyGeneratedKey12345
  Settings__Auth__Issuer: FrameUp
  Settings__Auth__Audience: http://svc-identity-app:8080
  Settings__LogBee__OrganizationId: 8a2de170-dd2c-4bed-b853-bec2ca7bbb5a
  Settings__LogBee__ApplicationId: bafc28c1-0059-4f9d-b19b-ccb0d7c0beb1
  Settings__LogBee__ApiUrl: logbee.backend.dev:44088
  ASPNETCORE_ENVIRONMENT: Development
  ASPNETCORE_HTTP_PORTS: "8080"