apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
      - name: order-service
        image: ghcr.io/team-one-pos-tech/frameup-order-service:latest
        ports:
          - containerPort: 8080
        env:
        - name: Settings__Auth__Audience
          value: "http://svc-identity-app:5001"
        envFrom:
            - configMapRef:
                name: configmap-order-service
        resources:
          requests:
            memory: "1Gi"
            cpu: "300m"

---
apiVersion: v1
kind: Service
metadata:
  name: svc-order-service
spec:
  selector:
    app: order-service
  ports:
  - name: order-service-port
    port: 5003
    targetPort: 8080
  type: LoadBalancer