apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  selector:
    matchLabels:
      app: postgres
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
